---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkding-superuser
  namespace: linkding
spec:
  encryptedData:
    LD_SUPERUSER_NAME: AgB4TR0C0xY+Mq2ifvqyRchAfCebOJ8NphB51U4ZhBJUK73E0xIp1gOFmo7fo0iv7w33RqtPQILvwCoZ3jgK+3+d05k5pveQDmFaHy6aRjvul1rPeR8eSWDfMs2xyNvkKAKdTYE+rj4xN7I0AL17S3fVvRWfZSJ2yV673SqOIVAix8xoCiPYbgZQETmOSgV50PZum6BovnV+cVnrVjMCFqeFxfrp2BZaIyVrM4CYVGX9t/zpCi7TzpfHIV2CpHnP8igVMOkt/rrqlGiG693Wp7rSUTD+uIWcgmFbHfSCVuZwNm7w9HgYq3mbnFLRYgo7Yiis1QRCQk8RKGp0Zd90iV1N5/sebepHUnP9aNoCARMz/egH/A1Mpg9dNxzmsgm0DNP7ZB+1hyzTcEM5gYsgjWzWsHeGfpvvV/3q0QkaeNlGvBdYikzzlvLxKmiEHllnEZg+B4DBt9XxHkdWTEzxcWrFjlAsyTpDDbXJHi9cW1R2NjN7svDm3QlQwLDWMupjQ/hv73iFgYfWm0fNyVzqPq9surgbiOSqK+Vk7Vg3rVT0fkly+gkn5hnhAU2oa0i1YfN3KlRfobhNZl9KaLg6FFxK19yDuKAanEEUgp/B8YCS9y2ghrnIw6XE13ee15+r0LgevyW7Rovo36S60Enga7yqUSIssFvrK3vyUZ257iQtOKmVzmE5t0W97+V3F2soHMdJHhubxQ==
    LD_SUPERUSER_PASSWORD: AgBZwdD9hhay+7fztgwuuDJBCXxyBfnp5Tqw2xO3M2gRhRHG2PtpbkOdEfv+h9HYuElBnLQrLIYp8JQ35uNMFrXVPAGRCVbQGDgFnoZ+QVNi4Bdg0PeN1BGgm2HKeRq7wSOCf/ZIo/9aOp77v4gdUt2LwJh7Vi6fku+a+/9YH0c74YFN9wvofqmji49Dtel4VxVG8jyHS8JmmbUuC52mWvjihyq4XtHWC5qwOccrHrW3gL0lVEnqWt8EKzvicBi1VBZCGy/w6Bqxzi3IdYCNjP4ucSA3DfEM5LhNV1C+6h+6ImBgUS98Po4AjSPH6/xQJE+zE5Zp6mQqcTnOvpGw9jpySKrZIxMm73m/UfBwlGnVmFMwiCx3zX0KiA4mQffdd86vLxAotyCSdSWwDgPphvt0E0FbAb2484UNp6LrUbPktGV7q73te5SYm3kXsewKI72B996SPRsWj1fDDuc4czg007OkC5DWIFzWiAUO8GZYy0MwRPLT9qeIQoAibEm3F7ecrl28KqmtPAC4NvBg99QBWUh4IDD5GLYDWxHPXE467kdCIeDJ8vMN0T4nACSvxZPEgMGoxPtD+YgFDRsePrgHTleEe4HEBtDthF8oZH49eQ91MngvyMGA2PyJNcJUXwjcwFoIaqpMaVVBKOgvySodOcBBBph4H+imfJs64bobOFKpw55TFMx99mTjgiNi5Jj9r1ftyQ==
  template:
    metadata:
      name: linkding-superuser
      namespace: linkding
