---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkding-superuser
  namespace: linkding
spec:
  encryptedData:
    LD_SUPERUSER_NAME: AgAwSeEDqJ8pysfNXTuWBYPAqu7eILS9hDVSlbsxfSQLjRDrlY6+lgHmNAv3nvCQEEQLGKypgMyCC5CNP0+7QeV++BAnob6ftF7WTYQBWM2vvHMg5BtECJk8SLfe4d5Z0QQ5WuinNttGvvkk2Vaw4CTK/MI9lnnaG7tM6nkdE1Pko1ytPL1F0I+toiKcdIvxW1Eb2OyHYiIscQLUsUwlxuEeR/lBZ4Q5gkDu5+B1NuRiAFqnKC/joYGE63vUsfRB5Np+B4yaGBVkUYkI+hhBKbgpT6WaW9ppyHVXZV4koB28YB5FhVUCK0xAHsrZaqJEouRD+CfMFxnfkHLTKjixwEPLXna9SjgfDP76zMfK8BWECwO6cW2wOcwekYIbwBvvi1+BaIF/ZrKApaudFEL7EYbczP33mguT6I28To/UVWRzuCr96BTUwkfOF/CtUxFLYHv9AWbL+xWKW5qHwuzxoubpJmEZPalrx+B+l52NtWYvXCkJfXmI6bvujPV58DmQkjeO3wjEEXgK3x6nF059P32xafHIrUU7fa4IB6emYWeuYcVHq43dryNoWeJgG1MPy45samxZChV6koO72qlQgTKD2Ct4LKnAZbLFrK8xZbcOxIlE3cmbVJKKyO/9M64fTeSdrden1PXnHJdBC15qKRHosZyGt0SCXq29Xunq7dBIr0MWSjJ33onPz6OP3Xf3249NukkicQ==
    LD_SUPERUSER_PASSWORD: AgCLZChEhEhW/RAfuFT4MA53JcFO7rUdxBWcDNOCb1aIB1SVVMB/4OrF6n+GmlcHHS3zxvf7UkTnWDgIUpoukKJExBbfhbS3QPqYIr5OGME0capQxYT/YZqdbayMaImExThBcl3gwhbRWYrJmznmTGhvVN0qFMD2bn8AaJKCzdnMFeuaj64nAiM0nuDXhp2+ThFBkRkaV1EyRQ97T30WK9hBs0YIaprh00Z+MnftO516ITqbptyJ/pvXLMxwIlaa1dzN/FbeGndDC4F+wwtdlEetCh1R14zt2CqAGsT3lnqWb6EhbJKR/m8dgmrPuv9NBQIo2lsNmkVzLQ8S8TBR0mbiM22ekbWihmuDy8Bw1j9wjrR3wysjtyz/CmZ7h21xHkv9sYppQ3uu5AhnvGMibmc7ARm+F7xbgBPMPq9dm0SwZ2qSY1U3tNmMivde/qi5qsHyBqf8116w9wkmcTj0j2bWV6Qh3c/QrJPhvztGm3kUsoYXtik80SjNtH11kKz3st0phGwVspn8OtTw4/iAJhmzQ7s8KkjgJy0qW2gWSo3v5L453xY2oQKSdOUyxv+BQC7Wf8cL9DMLf8/m1ctHwhUE/rl7fKMTAwxLJ6c/Z1G2O+jrMr35jqv7R9NtfUHGbrqgnbcDfdWSCmw0esMMzr1Ef0ffphoCH3GnotAECvuytEuSKDpqvM0Hp/78fEchiERGSFs8Zg==
  template:
    metadata:
      name: linkding-superuser
      namespace: linkding
