---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkding-superuser
  namespace: linkding
spec:
  encryptedData:
    LD_SUPERUSER_NAME: AgBucBXwSk/R4odypLEnb99QfRaRzWlQNs1rzLTI9A5mupqbJATa3jSDZXKBDyDqKB2PkaXcMAs+1QtGJ3oZ7kzI85PzU2XENGp5SPxNP6Cg+TA618kTrGSE7l2tzbiyg7bN3EB9RoxD1Pz+waPwGQHK+cu9DBTdHTPV6w5wmaEFyVfPaqdaNNm9dYsGynlWgrolAtrEUiYK+6QsUhKa0PtB9RUq63D6ktPBuslnsyBk4djwP8SUJZ84O4yb450d6FQGS1rlViqYgW9X59pzvYgdJIaOaCwrDi8ZKwWPrtOyKotfH3vXxDTLGamTGYFsoeRgTZj65gb58sVlRMn3VUVqc1+SPkxk5jgozXAj/xey7hQmDJOanz8NBvRFrQU/acAxeQ+3fh/RBUEwwNGyNqlLIKxP3bCTpEB7vIHZt/StnsyHQ6yf4O3BXx3WGJjcKPDD4qK51s0op+E9PWqjfG7WqL+v0MB2sGeN/yqlYJcqmJ/rpLHupq+ATCoKZpDErtOS0ND4d/c/XtYiBWS6zbfNYjLShtLa04ymFeipVsK1jS1MeFxJSuAc55EGiRBsaKiY/plML2QdW5Fy/q6voRxm8CMJl4N1zRINBP+EpgasntP3WCIZJo8VmpOx+/H6aOlhRLGFOPFUqmyN+Y4HzFYbvCiWn+fdFGmroU0LiqnlzWVlz0aVbmUCMJRGdrK9ctzyUS8KLQ==
    LD_SUPERUSER_PASSWORD: AgCMXLUzw+/uHKc7DpdnBRT78IQEsiQ7ws0DJKjYL7ggkct68KWzVfF/pED++YFhHxBZ9ij1ySicqHiQeEZxve7UK6t4bCI/Hc8yVy57+ozes7FEW3wPFYhQ7L+7qOsOKzgVfMlpXZwdSd3XUnJhfzQ0xOLwC6ih5FMky1gC2OLHzFEEbtdaWDOQDm+hU8/XrpHSbRYstE8CgWqf2qF04ua1XkYRZpcVUQcvE6rY4TWO76wAFRILy5CZMV+0dSeEci/ZjtFkZtRXzqsG7lEqozRfrQDAdy8mQYD9TYn793TBhaV4BIWA3ZMVoQRd0eZtANVtU8+o3CqLPZXQTUZfoNVFYxlI40/ZfXESrDN8gvxRe9Npr0u0egFlbHhAhYOEAnJkheaKW0D8LVAsdHXOiCcohdxPZItzURDIfTJK0MwSKeytMJUduNxcQ7yTVTI7OiFDDfdWNfykqEdhqhs+reQh4SYclK3ddRVwV6oW8WMz09L0bO1XU+r+KB8QDFFJP9maXndO00N1zo+aTd2vbGHl6oAUzSr9Sutrk8m6MJXOYz0GZ51K5qlug5cQ2sULC5ikGtbhCQ5Bsgzr0yDTO8qwN0u+TczzECHCIQHDGyYQ7g10oDAU6o5zUigxRRrWmBOpG8QjGhSG1zkReQaX391hj17Ufh+J8Et6Sm5keJY3qfIFld4HErjxDiSSDP+qSilBbj9XNg==
  template:
    metadata:
      name: linkding-superuser
      namespace: linkding
