apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linkding
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
      - image: sissbruecker/linkding:1.45.0
        name: linkding
        envFrom:
        - secretRef:
            name: linkding-superuser
        volumeMounts:
        - name: linkding-vol
          mountPath: /etc/linkding/data
      volumes:
      - name: linkding-vol
        persistentVolumeClaim:
          claimName: linkding-pvc
